const REQ_CONTACT_LIST = 'REQ_CONTACT_LIST';
const REQ_CONTACT_LIST_FAILURE = 'REQ_CONTACT_LIST_FAILURE';
const REQ_CONTACT_LIST_SUCCESS = 'REQ_CONTACT_LIST_SUCCESS';

const REQ_GET_CONTACT = 'REQ_GET_CONTACT';
const REQ_GET_CONTACT_FAILURE = 'REQ_GET_CONTACT_FAILURE';
const REQ_GET_CONTACT_SUCCESS = 'REQ_GET_CONTACT_SUCCESS';

const REQ_CREATE_CONTACT = 'REQ_CREATE_CONTACT';
const REQ_CREATE_CONTACT_FAILURE = 'REQ_CREATE_CONTACT_FAILURE';
const REQ_CREATE_CONTACT_SUCCESS = 'REQ_CREATE_CONTACT_SUCCESS';

const REQ_EDIT_CONTACT = 'REQ_EDIT_CONTACT';
const REQ_EDIT_CONTACT_FAILURE = 'REQ_EDIT_CONTACT_FAILURE';
const REQ_EDIT_CONTACT_SUCCESS = 'REQ_EDIT_CONTACT_SUCCESS';

const REQ_DELETE_CONTACT = 'REQ_DELETE_CONTACT';
const REQ_DELETE_CONTACT_FAILURE = 'REQ_DELETE_CONTACT_FAILURE';
const REQ_DELETE_CONTACT_SUCCESS = 'REQ_DELETE_CONTACT_SUCCESS';

export {
  REQ_CONTACT_LIST,
  REQ_CONTACT_LIST_SUCCESS,
  REQ_CONTACT_LIST_FAILURE,
  REQ_GET_CONTACT,
  REQ_GET_CONTACT_SUCCESS,
  REQ_GET_CONTACT_FAILURE,
  REQ_CREATE_CONTACT,
  REQ_CREATE_CONTACT_SUCCESS,
  REQ_CREATE_CONTACT_FAILURE,
  REQ_EDIT_CONTACT,
  REQ_EDIT_CONTACT_SUCCESS,
  REQ_EDIT_CONTACT_FAILURE,
  REQ_DELETE_CONTACT,
  REQ_DELETE_CONTACT_SUCCESS,
  REQ_DELETE_CONTACT_FAILURE,
};
