const REQ_CONTACT_LIST = 'REQ_CONTACT_LIST';
const REQ_CONTACT_LIST_FAILURE = 'REQ_CONTACT_LIST_FAILURE';
const REQ_CONTACT_LIST_SUCCESS = 'REQ_CONTACT_LIST_SUCCESS';

export {
    REQ_CONTACT_LIST,
    REQ_CONTACT_LIST_SUCCESS,
    REQ_CONTACT_LIST_FAILURE
}
